__author__ = 'Steve'

from sae.const import MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASS, MYSQL_DB

DB_NAME = MYSQL_DB
DB_USER = MYSQL_USER
DB_PASSWORD = MYSQL_PASS
DB_HOST = MYSQL_HOST
DB_PORT = MYSQL_PORT
